services:
  db:
    container_name: dex-db
    image: postgres:18
    environment:
      POSTGRES_USER: dex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
