services:
  db:
    container_name: rustack-db
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustack
    ports:
      - "5432:5432"
